[profile.default]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
ffi = true
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./test"}]
